Repository HackPlan/UUI, pull requests merged in 2020-07, with the labels that each got.

#12 Fixed the potentially uncontrolled problem of TextArea
  src/components/Input/TextArea.tsx
Labels: bug

#11 Feature/loading
  src/components/Button/Button.tsx
  src/components/Cascader/Cascader.tsx
  src/components/Input/NumberField.tsx
  src/components/Input/TextArea.tsx
  src/components/Input/TextField.tsx
  src/components/Loading/LoadingCover.tsx
  src/components/Loading/LoadingSpinner.tsx
  src/components/Loading/index.ts
  src/components/Pagination/PageInfo.tsx
  src/components/Pagination/PageJumper.tsx
  src/components/Pagination/PageList.tsx
  src/components/Pagination/PageNextButton.tsx
  src/components/Pagination/PagePrevButton.tsx
  src/components/Pagination/PageSelector.tsx
  src/components/Pagination/PageSize.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Select/HTMLSelect.tsx
  src/components/Select/Select.tsx
  src/components/Switch/Switch.tsx
  src/components/Table/Table.tsx
  src/index.ts
  src/styles/components/Button.scss
  src/styles/components/Cascader.scss
  src/styles/components/HTMLSelect.scss
  src/styles/components/Loading.scss
  src/styles/components/NumberField.scss
  src/styles/components/Pagination.scss
  src/styles/components/Select.scss
  src/styles/components/Switch.scss
  src/styles/components/TextArea.scss
  src/styles/components/TextField.scss
  src/styles/index.scss
  stories/Button.stories.mdx
  stories/Loading.stories.mdx
  stories/Switch.stories.mdx
  webpack.config.js
Labels: component, enhancement, feature

#6 Storybook 6.0.0
  .storybook/main.js
  package.json
  src/components/Popover/Popover.tsx
  stories/Drawer.stories.mdx
  stories/Drawer.stories.tsx
  stories/Form.stories.mdx
  stories/Form.stories.tsx
  stories/Icon.stories.mdx
  stories/Icon.stories.tsx
  stories/Layout.stories.mdx
  stories/Layout.stories.tsx
  stories/Table.stories.mdx
  stories/Tag.stories.mdx
  stories/Toast.stories.mdx
  stories/Toast.stories.tsx
  yarn.lock
Labels: dependencies, enhancement
